
---    
   
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-gitrepo-v0.3
spec:
  replicas: 2
  selector:
    app: website-from-git
    ver: 0-3
    
  template:
    metadata:
      labels:
        app: website-from-git
        ver: 0-3
    spec:
      containers:
      - name: nginx
        image: ckleban/nginx-from-git:v2
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /wwwdata
          name: gitdata
        resources:
          requests:
            cpu: "250m"
            mem: "128Mi"
          limits:
            cpu: "250m"
            mem: "256Mi"
      volumes:
      - name: gitdata
        gitRepo:
          Repository: https://github.com/ckleban/sample-website
          Revision: aaf7ea4beb9771468b6729bc041dd567dff2f472

