
---    
   
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-gitrepo-v0.1
spec:
  replicas: 2
  selector:
    app: website-from-git
    ver: 0.1
    
  template:
    metadata:
      labels:
        app: website-from-git
        ver: 0.1
    spec:
      containers:
      - name: nginx
        image: ckleban/nginx-from-git:v2
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /wwwdata
          name: gitdata
      volumes:
      - name: gitdata
        gitRepo:
          Repository: https://github.com/ckleban/sample-website
          Revision: 2fce3f52f28b0eb52fe2fd4fdec34eceab05122f

