
---    
   
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-gitrepo
spec:
  replicas: 2
  
  selector:
    app: website-from-git
    deployment: v1
    
  template:
    metadata:
      labels:
        app: website-from-git
        deployment: v1
    spec:
      containers:
      - name: nginx
        image: ckleban/nginx-from-git:v1
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /wwwdata
          name: gitdata
      volumes:
      - name: gitdata
        gitRepo:
          Repository: https://github.com/ckleban/sample-website

   
# /usr/share/nginx/html