 
apiVersion: v1
kind: Service
metadata:
  name: website1-nodeport
  labels:
    app: website-from-git

spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: website-from-git
    

   
   